### PR TITLE
Laravel 8 Fix

### PR DESCRIPTION
**Pull request by hasnhasan**

### CODE REVIEW

**Comment by mylemans** [comment]
@tylernathanreed Is this not accepted yet for a specific reason?

**Comment by ahfa92** [comment]
@tylernathanreed we need this for laravel 8.12

**Comment by ahfa92** [comment]
@tylernathanreed  I'm sorry I need this fast so I forked and change the package name only. All credits still to you.

**Comment by tylernathanreed** [comment]
@ahfa92 The PR has been accepted.

**Comment by ahfa92** [comment]
@tylernathanreed  thank you

**Pull request merged**
